### ISSUE TITLE
gRPC Inactive RPC Error when trying to connect to Reachy's IP

### ISSUE THREAD

**Issue by PRISHIta123** [pollen-robotics/reachy-sdk#46]
Hi all, we’ve been working on reachy without problem and we suddenly have an InactiveRPCError message today when trying to connect through ip.  We tried both the local computer (“127.0.0.1”) and through network, both not work. We checked the server status and motor status, both are okay. Any suggestions?

`Traceback (most recent call last):
  File "PredictOP.py", line 399, in <module>
    reachy = ReachySDK('127.0.0.1')
  File "/home/reachy/dev/reachy-sdk/reachy_sdk/reachy_sdk.py", line 75, in __init__
    self._setup_joints()
  File "/home/reachy/dev/reachy-sdk/reachy_sdk/reachy_sdk.py", line 104, in _setup_joints
    joint_ids = joint_stub.GetAllJointsId(Empty())
  File "/home/reachy/.local/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/reachy/.local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1656018785.748839372","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3008,"referenced_errors":[{"created":"@1656018785.748837968","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
`

**Comment by PRISHIta123** [comment]
@simheo @pierre-rouanet could you please help us with this?

**Comment by simheo** [comment]
Closing this issue as your problem is not software related.
