### ISSUE TITLE
Wrong wrist angle: -150deg to -25deg

### ISSUE THREAD

**Issue by francescamaenza** [pollen-robotics/reachy-sdk#57]
Hello Reachy team

We're the EPFL team working with Reachy 2019 (upgraded to 2021 using a NUC instead of the raspi).
We're currently controlling its left arm using the inverse_kinematic function from Reachy SDK ver. 0.5.4.

We had to change the left arm-gripper connector (i.e., wrist-hand module in the Reachy 6-Dofs bio-inspired Arm cad) after it broke during a collision with the experiment table. We replaced the part with one we printed, but after the replacement, we found that the wrist pitch angle has a range from -150 to -30 degrees (read from get present_position function), instead of from -45 to +45 (as specified in the documentation). 

Do you have any idea what could be the cause of the wrong wrist range?

Thank you for your help and your effort in making Reachy.

**Comment by aidengk-iris** [comment]
Huge thanks to Annaëlle Segré's suggestion on discord. We corrected the wrist angle by making sure the motor "horn" (or bearing?) is correctly aligned with certain marks. 
Annaëlle's suggestion is included here, in case other people encounter the same issue.

![image](https://github.com/pollen-robotics/reachy-sdk/assets/85515041/f807cdcf-9d55-4401-a965-66f81c5d3cdf)

**Comment by pierre-rouanet** [comment]
Thank you for including her answer here!
